Error: set(['a']) called inside f is not defined